export  default {
    MARK_HAS_READ_BY_ID:'MARK_HAS_READ_BY_ID',
    MARK_ALL_HAS_READ_BY_ID: 'MARK_ALL_HAS_READ_BY_ID',
    START_LOADING:'START_LOADING',
    FINSH_LOADING:'FINSH_LOADING',
    GET_INFOS_FROM_BACK:'GET_INFOS_FROM_BACK',
    START_LOGIN:'START_LOGIN',
    LOGIN_FAILE:'LOGIN_FAILE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS'
}